### ISSUE TITLE
Base contains proprietary software

### ISSUE THREAD

**Issue by LudvikGalois** [anucssa/installfest-2015#1]
Whilst I'm all for including a decent text editor, there's really no reason why it should be in base. It is not essential for any single course, and differs from what is on the lab machines.

**Comment by ajdlinux** [comment]
I'm inclined to agree here; separate it out and install a good free software text editor in base. Because freedom!

(also because I'm increasingly becoming convinced that Sublime Text is as much of a cult as emacs)

**Comment by tsujamin** [comment]
fixed in https://github.com/anucssa/installfest-2015/commit/60003d88f32784d27d13a0b1e60ca6246af428b3. While an editor such as sublime or atom is not essential _for any single course_ I would say that a more (out of the box) user friendly editor of some variety is essential.

Installfest-2015 S1 images have been built, can't guarantee they will be rebuilt with this change. Time permitting I may.
